# Generated by Django 3.2.9 on 2021-11-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPosts', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=4000),
        ),
    ]
